services:
  db: 
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret-pw
      PG_DATA: /data/postgres
    volumes:
      - ./docker/postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes: 
  postgres:

